############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: ${framework.web.session.token-name}
  # token前缀，例如填写 Bearer 实际传参 satoken: Bearer xxxx-xxxx-xxxx-xxxx
  # token-prefix: Bearer

  # token 有效期（单位：秒） 默认30天，-1 代表永久有效 30天后直接过期
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: ${framework.web.session.timeout}
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid

  # 是否尝试从 header 里读取 Token
  is-read-header: true
  # 是否在登录后将 Token 写入到响应头
  is-write-header: ${framework.web.session.write-header}
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  is-read-cookie: true
  #jwt秘钥 （只有集成 sa-token-temp-jwt 模块时此参数才会生效）
  #https://sa-token.cc/doc.html#/plugin/jwt-extend
  #jwt-secret-key: 46451515

  # 是否输出操作日志
  is-log: true
  # 日志等级（trace、debug、info、warn、error、fatal），此值与 logLevelInt 联动
  log-level: info

